[workspace]
default-members = ["hello_world"]
members = ["hello_world", "guessing_game"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kevin Rodriguez"]
description = "my personal set of exercises"
